# Generated by Django 5.2.10 on 2026-01-28 21:35

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx', 'xls']), core.models.validate_file_size]),
        ),
    ]
