# Generated by Django 5.2.10 on 2026-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evidenceitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerecord',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='revoked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
